import { Document, Paragraph, TextRun, HeadingLevel, Table, TableCell, TableRow, WidthType, BorderStyle, Packer } from 'docx';
import { saveAs } from 'file-saver';

interface ExportSection {
  type: 'heading' | 'paragraph' | 'table' | 'list';
  content: string;
  level?: 1 | 2 | 3;
  tableData?: string[][];
  listItems?: string[];
}

interface ExcelAnswerExport {
  question: string;
  answer: string;
  cellReferences?: { sheet: string; cell: string; value: string }[];
  chartDescription?: string;
}

/**
 * Export an Excel analysis answer to a DOCX file
 */
export async function exportExcelAnswerToDocx(
  data: ExcelAnswerExport,
  fileName: string = 'excel-analysis'
): Promise<void> {
  const doc = new Document({
    sections: [{
      properties: {},
      children: [
        // Title
        new Paragraph({
          text: 'Excel Analysis Report',
          heading: HeadingLevel.HEADING_1,
          spacing: { after: 400 },
        }),
        
        // Question
        new Paragraph({
          text: 'Question:',
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 200, after: 100 },
        }),
        new Paragraph({
          children: [
            new TextRun({
              text: data.question,
              italics: true,
            }),
          ],
          spacing: { after: 200 },
        }),
        
        // Answer
        new Paragraph({
          text: 'Answer:',
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 200, after: 100 },
        }),
        ...data.answer.split('\n').map(line => 
          new Paragraph({
            children: [new TextRun({ text: line })],
            spacing: { after: 100 },
          })
        ),
        
        // Cell References
        ...(data.cellReferences && data.cellReferences.length > 0 ? [
          new Paragraph({
            text: 'Referenced Cells:',
            heading: HeadingLevel.HEADING_2,
            spacing: { before: 300, after: 100 },
          }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              new TableRow({
                children: [
                  new TableCell({
                    children: [new Paragraph({ text: 'Sheet', heading: HeadingLevel.HEADING_3 })],
                    width: { size: 25, type: WidthType.PERCENTAGE },
                  }),
                  new TableCell({
                    children: [new Paragraph({ text: 'Cell', heading: HeadingLevel.HEADING_3 })],
                    width: { size: 25, type: WidthType.PERCENTAGE },
                  }),
                  new TableCell({
                    children: [new Paragraph({ text: 'Value', heading: HeadingLevel.HEADING_3 })],
                    width: { size: 50, type: WidthType.PERCENTAGE },
                  }),
                ],
              }),
              ...data.cellReferences.map(ref => 
                new TableRow({
                  children: [
                    new TableCell({ children: [new Paragraph({ text: ref.sheet })] }),
                    new TableCell({ children: [new Paragraph({ text: ref.cell })] }),
                    new TableCell({ children: [new Paragraph({ text: ref.value })] }),
                  ],
                })
              ),
            ],
          }),
        ] : []),
        
        // Chart Description
        ...(data.chartDescription ? [
          new Paragraph({
            text: 'Visualization:',
            heading: HeadingLevel.HEADING_2,
            spacing: { before: 300, after: 100 },
          }),
          new Paragraph({
            children: [new TextRun({ text: data.chartDescription })],
            spacing: { after: 100 },
          }),
        ] : []),
        
        // Footer
        new Paragraph({
          children: [
            new TextRun({
              text: `Generated by Gyankosh on ${new Date().toLocaleDateString()}`,
              size: 20,
              color: '666666',
            }),
          ],
          spacing: { before: 400 },
        }),
      ],
    }],
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, `${fileName}.docx`);
}

/**
 * Export a full chat conversation about Excel data
 */
export async function exportExcelChatToDocx(
  messages: { role: 'user' | 'assistant'; content: string }[],
  excelFileName: string,
  fileName: string = 'excel-chat-export'
): Promise<void> {
  const children: Paragraph[] = [
    new Paragraph({
      text: `Excel Analysis: ${excelFileName}`,
      heading: HeadingLevel.HEADING_1,
      spacing: { after: 400 },
    }),
  ];

  messages.forEach((msg, idx) => {
    children.push(
      new Paragraph({
        text: msg.role === 'user' ? '📝 Your Question:' : '🤖 Analysis:',
        heading: HeadingLevel.HEADING_2,
        spacing: { before: idx > 0 ? 300 : 0, after: 100 },
      })
    );

    msg.content.split('\n').forEach(line => {
      children.push(
        new Paragraph({
          children: [new TextRun({ text: line })],
          spacing: { after: 50 },
        })
      );
    });
  });

  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: `Exported from Gyankosh on ${new Date().toLocaleDateString()}`,
          size: 20,
          color: '666666',
        }),
      ],
      spacing: { before: 400 },
    })
  );

  const doc = new Document({
    sections: [{ properties: {}, children }],
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, `${fileName}.docx`);
}
